"""init db

Revision ID: f92eda573ddf
Revises: 
Create Date: 2018-03-08 23:56:39.773977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92eda573ddf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('job_name', sa.String(length=32), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=False),
    sa.Column('salary_max', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('exp', sa.String(length=16), nullable=False),
    sa.Column('education', sa.String(length=16), nullable=False),
    sa.Column('stacks', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=32), nullable=True),
    sa.Column('tags', sa.String(length=64), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_job_name'), 'job', ['job_name'], unique=False)
    op.create_table('user_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=True),
    sa.Column('resume', sa.String(length=128), nullable=True),
    sa.Column('website', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('logo', sa.String(length=256), nullable=True),
    sa.Column('finance_stage', sa.String(length=128), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('profile', sa.String(length=1024), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_base_email'), 'user_base', ['email'], unique=True)
    op.create_index(op.f('ix_user_base_phone'), 'user_base', ['phone'], unique=True)
    op.create_index(op.f('ix_user_base_username'), 'user_base', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_base_username'), table_name='user_base')
    op.drop_index(op.f('ix_user_base_phone'), table_name='user_base')
    op.drop_index(op.f('ix_user_base_email'), table_name='user_base')
    op.drop_table('user_base')
    op.drop_index(op.f('ix_job_job_name'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
